# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 514164707815.dkr.ecr.us-east-1.amazonaws.com/holdencloud/event-metric-service
  tag: 0.0.9
  pullPolicy: IfNotPresent

# define environment variables here as a map of key: value
env:

envSecrets:
  - name: MONGO_USERNAME
    secret:
      name: mongo-credentials
      key: username
  - name: MONGO_PASSWORD
    secret:
      name: mongo-credentials
      key: password
  - name: MONGO_DATABASE
    secret:
      name: mongo-credentials
      key: database_name

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

service:
  name: event-metric-service
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "false"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
